training:
  num_epochs: 5
  batch_size: 256
  initial_lr: 0.0001
  transform_choice: 1
  use_ddp: True
  use_amp: True

model:
  num_classes: 10
  dropout_rate: 0.3

data:
  dataset_path: './data'
  train_val_split: 0.8
  num_workers: 4

device: 'cuda'