training:
  num_epochs: 8
  batch_size: 64
  initial_lr: 0.0001
  transform_choice: 1

model:
  num_classes: 10
  dropout_rate: 0.3

data:
  dataset_path: './data'
  train_val_split: 0.8
  num_workers: 10

device: 'cuda'