name: Auto Train on Merge

on:
  push:
    branches:
      - main  # Trigger when changes are merged into main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Training Script
        run: |
          python train.py  # Make sure this script is set up to log to Weights & Biases
