name: Evaluate Model

on:
  push:
    branches: [ "evaluation" ]
  pull_request:
    branches: [ "evaluation" ]

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run evaluation script
        run: |
          python evaluate.py
